version: '2'

services:
  item-app:
    image: dannyferdiansyah/item-app:v1
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "80:80"
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db:

